spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: microservice1
          uri: http://localhost:9191
          predicates:
            - Path=/callme1/**
        - id: microservice1
          uri: http://localhost:9192
          predicates:
            - Path=/callme2/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/dev
        registration:
          dev:
            provider: keycloak
            client-id: dev
            client-secret: 9ZYx19OD64aRZrX3Qbyrtlj0HfocrwGV
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

server.port: 8060

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE